name: build

on: [push]

jobs:
    build:
        runs-on: macos-latest

        strategy:
            matrix:
                node-version: [10.x, 12.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install TypeScript globally
              run: npm install typescript -g

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build
